services:
  - type: web
    name: job-match
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: $PORT
      - key: FLASK_SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true 